superdesk/newsroom-core

newsroom/email.py
newsroom/templates/email_layout.html
newsroom/templates/share_topic.html
newsroom/templates/signup_request_email.html
newsroom/templates/signup_request_email.txt
newsroom/topics/views.py
tests/core/test_topics.py

add missing html email templates

---

assets/search/selectors.js
assets/styles/index.scss
assets/wire/components/ItemsList.jsx
assets/wire/components/WireListItem.jsx

Don't show match label for neweset version
[NHUB-24]: Don't show match label if search is not filtered
[NHUB-24]: https://sofab.atlassian.net/browse/NHUB-24?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NHUB-39] Show matches in version link for wire list items

---

newsroom/web/default_settings.py
newsroom/wire/search.py

allow embargoed items on dashboard

---

assets/wire/components/PreviewTags.jsx

- and change subject label from category to subject
TGA-6

add service to preview tags

---

newsroom/gettext.py
newsroom/template_filters.py
newsroom/web/factory.py

allow locale specific sidenav

---

newsroom/search.py

fix search count returned when there are matching embargoed items

---

assets/maps/components/static.jsx
assets/ui/components/ArticlePicture.jsx
assets/wire/components/WireListItem.jsx
package-lock.json
package.json

add missing alt to img elements

---

assets/home/components/HomeApp.jsx
assets/ui/selectors.js
newsroom/agenda/views.py
newsroom/am_news/views.py
newsroom/companies/views.py
newsroom/factcheck/views.py
newsroom/market_place/views.py
newsroom/media_releases/views.py
newsroom/monitoring/views.py
newsroom/ui_config.py
newsroom/wire/views.py

make home search configurable

---

newsroom/__init__.py
newsroom/media_utils.py
newsroom/push.py
newsroom/web/default_settings.py
newsroom/web/factory.py

fix generating renditions for non featuremedia assoc

---

assets/analytics.js
assets/utils.js

fix analytics page view reporting

---

newsroom/factory/app.py
newsroom/web/default_settings.py

setup sentry in app factory

---

newsroom/push.py
newsroom/web/default_settings.py
tests/core/test_push.py

based on config it will filter out subjects which
are not used and should not be visible.
NHUB-63

allow filtering of subjects before storing

---

assets/home/components/search-bar.jsx

only display it when there is value to be cleared
CPNHUB-28

fix dashboard search clear button

---

assets/home/components/HomeApp.jsx
assets/home/reducers.js
assets/wire/components/ItemDetails.jsx
assets/wire/components/ItemsList.jsx
assets/wire/components/PreviewMeta.jsx
assets/wire/components/WireApp.jsx
assets/wire/components/WireListItem.jsx
assets/wire/components/WirePreview.jsx
assets/wire/components/fields/UrgencyLabel.jsx
newsroom/wire/views.py

implement field label handling for urgency

---

newsroom/factory/app.py
newsroom/web/default_settings.py

to add client specific translations
CPNHUB-79

add TRANSLATIONS_PATH config

---

newsroom/auth_server/oauth2.py
tests/core/test_oauth_clients.py

NHUB-103 FIX: token generation working for both type of client authentication.

---

assets/search/components/TopicEditor.jsx
newsroom/users/views.py

Also reload the Topics after a subscription change

[NHUB-93] fix: Invalid subscriber ID on creating a topic

---

newsroom/auth/views.py

increase rate limit on login

---

assets/companies/components/Companies.jsx
assets/navigations/components/Navigations.jsx
assets/products/components/Products.jsx
assets/section-filters/components/SectionFilters.jsx
assets/users/components/Users.jsx
messages.pot

add missing gettext calls to error messages

---

assets/utils.js
messages.pot

use gettext for agenda preview time

---

assets/components/cards/render/CardFooter.jsx
assets/components/cards/render/CardMeta.jsx
assets/components/cards/render/LargePictureTextCard.jsx
assets/components/cards/render/LargeTextOnlyCard.jsx
assets/components/cards/render/PictureTextCard.jsx
assets/components/cards/render/TextOnlyCard.jsx
assets/components/cards/render/TopNewsOneByOneCard.jsx
assets/components/cards/render/TopNewsTwoByTwoCard.jsx
assets/home/components/HomeApp.jsx
assets/wire/components/WireListItemIcons.jsx
assets/wire/utils.js

fix icons/download on dashboard

---

assets/utils.js

seems like `updateLocale` sets the locale to be `fr-ca`
CPNHUB-116

fix french date format when using en localization

---

assets/components/NotificationList.jsx
assets/styles/navbar.scss
assets/utils.js
assets/websocket.js

Additionally, share a global connection between redux stores/dispatches

[NHUB-123] fix: Automatically reconnect to websocket server

---

data_updates/00003_20211118-181158_topics.py
data_updates/00004_20220104-143720_topics.py

- delete topics of non-existing users
close #139

fix topics related data migrations

---

assets/agenda/components/AgendaListItemLabels.jsx
assets/agenda/components/AgendaPreview.jsx
assets/agenda/components/AgendaTime.jsx
assets/styles/index.scss
assets/ui/components/Article.jsx
assets/utils.js

avoid different components rendering date,
it will be always done by the agenda time.
CPNHUB-117

simplify agenda time component

---

assets/layout/components/BaseApp.jsx
assets/local-store.js
assets/wire/components/SearchSidebar.jsx
newsroom/web/default_settings.py

Also remember open state in browser local storage

[NHUB-127] Make FilterPanel open/tab defaults configurable

---

newsroom/web/default_settings.py

make elastic count above 10k

---

assets/layout/components/BaseApp.jsx
assets/wire/types.js

when coverage is opened via agenda
NHUB-116

fix blank page when closing edit topic modal

---

assets/navigations/components/EditNavigation.jsx
messages.pot

only show tile images in navigation if aap marketplace is enabled

---

assets/agenda/components/AgendaItemTimeUpdater.jsx
assets/agenda/components/AgendaList.jsx
assets/agenda/utils.js
assets/components/AuditInformation.jsx
assets/components/CalendarButton.jsx
assets/utils.js

fix fr-ca localisation

---

assets/components/cards/render/CardBody.jsx
assets/components/cards/render/LargePictureTextCard.jsx
assets/components/cards/render/LargeTextOnlyCard.jsx
assets/components/cards/render/PictureTextCard.jsx
assets/components/cards/render/TextOnlyCard.jsx
assets/components/cards/render/TopNewsOneByOneCard.jsx
assets/components/cards/render/TopNewsTwoByTwoCard.jsx
assets/wire/components/WireListItem.jsx
assets/wire/utils.js

use config for displaying abstract in the lists

---

newsroom/celery_app.py
newsroom/web/default_settings.py

- set global time limit
- log when there is an error/timeout
NHUB-151

fix celery config

---

newsroom/celery_app.py
newsroom/email.py

created the new class but didn't use it.
also fixed a bug in celery error reporting.
NHUB-152 CPNHUB-132

make use of NewsroomMessage

---

assets/components/AuditInformation.jsx
assets/utils.js
messages.pot

- fix gettext extraction
- add missing date to agenda preview
CPNHUB-79

fix localization

---

newsroom/agenda/__init__.py
newsroom/agenda/utils.py
newsroom/email.py
newsroom/templates/email_agenda.html
newsroom/templates/email_agenda.txt
newsroom/templates/email_watched_agenda.html
newsroom/templates/email_watched_agenda.txt
newsroom/wire/views.py

Also improve distinction between Event and Planning descriptions/sections

[CPNHUB-125] fix(email): Missing coverage date, language and empty map image

---

assets/agenda/components/AgendaCoverages.jsx
assets/agenda/components/AgendaListCoverageItem.jsx
assets/agenda/utils.js

to be in sync with list
NHUB-125

add coverage tooltips to preview

---

assets/agenda/components/CoverageItemStatus.jsx
assets/agenda/utils.js
messages.pot

the adjective is different based on noun
CPNHUB-79

improve fr_CA translation

---

newsroom/auth/saml.py

fix redirect on saml auth error

---

assets/agenda/components/AgendaListCoverageItem.jsx
messages.pot

to be translatable to fr
CPNHUB-79

update coverage tooltip text

---

newsroom/email.py
tests/core/test_emails.py

so now it will reformat those before printing html
CPNHUB-132

there could be still long lines inside html tags

---

assets/layout/components/BaseApp.jsx

hide sidebar when rendering saved items

---

assets/agenda/reducers.js
assets/wire/components/filters/FiltersTab.jsx

atm it's changing the date filter so what you get before using a filter and after is not consistent.
NHUB-163

tweak clear filters behaviour

---

assets/companies/components/CompanyListItem.jsx
assets/utils.js

it was showing different values based on the timezone, so avoid that and only display date there
NHUB-188

avoid working with time for company expiry

---

assets/ui/components/ArticleMedia.jsx
assets/wire/actions.js
newsroom/upload.py

always use rest api for download no matter where the rendition is stored.
NHUB-190

fix download media stored on amazon

---

assets/agenda/components/AgendaListItem.jsx
assets/local-store.js
assets/monitoring/index.js

fix agenda item visited status

---

assets/components/ListBar.jsx
assets/monitoring/components/MonitoringApp.jsx

fix missing button label in monitoring settings

---

newsroom/auth/token.py
newsroom/auth/utils.py
newsroom/auth/views.py
newsroom/decorator.py
newsroom/types.py
newsroom/users/users.py
newsroom/users/views.py
newsroom/utils.py
tests/core/test_auth.py
tests/core/test_users.py

- remove duplicated code in view/utils
- move utils from view to utils
- avoid using cache when authenticating, but add `auth_ttl` to session and consider it valid until it expires (then check again via db)
- add helpers for session handling

refactor auth code

---

assets/agenda/actions.js
assets/agenda/components/AgendaApp.jsx
assets/agenda/components/AgendaCoverages.jsx
assets/agenda/components/AgendaFilters.jsx
assets/agenda/components/AgendaItemTypeFilter.jsx
assets/agenda/components/AgendaListCoverageItem.jsx
assets/agenda/components/AgendaListItemIcons.jsx
assets/agenda/reducers.js
assets/agenda/utils.js
assets/companies/components/CompanyPermissions.jsx
assets/reducers.js
assets/search/actions.js
assets/websocket.js
assets/wire/actions.js
features/web_api/agenda_restrict_coverage_details.feature
newsroom/__init__.py
newsroom/agenda/agenda.py
newsroom/agenda/utils.py
newsroom/agenda/views.py
newsroom/companies/companies.py
newsroom/companies/utils.py
newsroom/companies/views.py
newsroom/email.py
newsroom/push.py
newsroom/templates/download_agenda.txt
newsroom/tests/web_api/steps.py
newsroom/utils.py
tests/core/test_download.py
tests/core/test_push.py
tests/core/test_push_events.py

Depends on https://github.com/superdesk/superdesk-core/pull/2394

[NHUB-195] New privilege to restrict coverage details

---

assets/agenda/components/AgendaMeta.jsx

fix links for websites like `www.example.com`

---

assets/agenda/components/AgendaTime.jsx

for all_day and no_end_time events
NHUB-197

fix event date display for original timezone

---

assets/agenda/components/AgendaEdNote.jsx

Avoid `Event Cancelled` string in french

---

assets/notifications/components/notificationItems.jsx
messages.pot

make notifications timestamps translatable to fr

---

assets/utils.js
messages.pot

which could make it go up/down one day, so now avoid that using moment utc mode which will display it as it is stored.
CPNHUB-161

it was converting the timestamps to local timezone

---

messages.pot
newsroom/web/default_settings.py
setup.cfg

mark coverage types names for translations

---

assets/agenda/components/AgendaCoverages.jsx
assets/agenda/utils.js
newsroom/agenda/views.py

Also fix an issue with coverage info leaking from Wire preview

[NHUB-200] ui: Improve coverage preview when info restricted

---

assets/agenda/components/AgendaEdNote.jsx
assets/agenda/utils.js

and also action prefix in case there is none
NHUB-210 NHUB-211 CPNHUB-170

fix errors in AgendaEdNote component

---

newsroom/agenda/agenda.py
newsroom/search.py
newsroom/search_config.py
tests/core/test_search_config.py
tests/search/test_search_filters.py

use WIRE_GROUPS config to figure out if field needs a nested filter.
STTNHUB-195

fix filtering based on fields with nested config

---

newsroom/push.py
tests/core/test_push.py

restore the format of new_item notification for wire

---

newsroom/agenda/utils.py

when coverages are `None` it would throw an error
NHUB-211

fix agenda detail for public user

---

newsroom/agenda/agenda.py
newsroom/push.py
tests/core/test_push_events.py

and populate those on push
CPNHUB-178

add language and source fields to agenda

---

newsroom/agenda/agenda.py

enable aggregations on language field in agenda

---

newsroom/agenda/agenda.py

fix elastic or query not working with recent elastic

---

newsroom/agenda/agenda.py
requirements.txt
tests/core/test_agenda.py
tests/core/test_search_config.py

avoid using elastic or query

---

newsroom/push.py
tests/core/test_push_events.py

The code was originally searching for the Event using the attributes ``event_item`` and ``guid`` of the Planning item in the one query. Default sort is ``dates.start``, and therefor would return the Planning item if the Planning date is before the Event start date. Meaning the Event would not be updated with the new Planning item (and it's coverages)

[CPNHUB-190] fix(push): Unable to find Event if Plan date is before Event start date

---

assets/agenda/tests/utils.spec.js
assets/agenda/utils.js
assets/utils.js

show all planned coverages in the list
and fix the time display for all day events
CPNHUB-188

fix coverage icon display in list

---

newsroom/signals.py
newsroom/users/users.py
tests/core/test_users.py

add signals for user create/update/delete

---

assets/company-admin/components/CompanyAdminApp.jsx
assets/company-admin/components/CompanyAdminProductSeatRequestModal.jsx
assets/company-admin/components/CompanyUsers.jsx
assets/company-admin/reducers.js
assets/company-admin/selectors.js
data_updates/00002_20200305-135244_agenda.py
data_updates/00005_20220203-151131_products.py
data_updates/00006_20220223-155546_products.py
data_updates/00007_20220502-134524_products.py
data_updates/00008_20220526-165600_users.py
data_updates/00009_20230116-145407_products.py
newsroom/agenda/formatters/ical_formatter.py
newsroom/auth/utils.py
newsroom/monitoring/formatters/rtf_formatter.py
newsroom/news_api/products/resource.py
newsroom/push.py
newsroom/wire/formatters/base.py
newsroom/wire/formatters/json.py
newsroom/wire/formatters/newsmlg2.py
newsroom/wire/formatters/nitf.py
newsroom/wire/formatters/picture.py
newsroom/wire/formatters/text.py

Also the ProductSeatRequest modal was showing all Sections/Products regardless of Company Permissions

[CPCN-81] fix: CompanyAdmin page crashes if user products is empty

---

assets/index.js
assets/styles/index.scss
data_updates/00002_20200305-135244_agenda.py
data_updates/00005_20220203-151131_products.py
data_updates/00006_20220223-155546_products.py
data_updates/00007_20220502-134524_products.py
data_updates/00008_20220526-165600_users.py
newsroom/agenda/formatters/ical_formatter.py
newsroom/auth/utils.py
newsroom/commands/create_user.py
newsroom/monitoring/formatters/rtf_formatter.py
newsroom/news_api/products/resource.py
newsroom/push.py
newsroom/wire/formatters/base.py
newsroom/wire/formatters/json.py
newsroom/wire/formatters/newsmlg2.py
newsroom/wire/formatters/nitf.py
newsroom/wire/formatters/picture.py
newsroom/wire/formatters/text.py

to avoid conflicts with out styles
NHUB-248

only add styles for skeleton from primereact

---

newsroom/products/products.py
newsroom/tests/fixtures.py
tests/core/test_products.py
tests/utils.py

delete refs to product when product is deleted

---

assets/common.js
assets/utils.js

it was loaded in common.js which was before the values were set on window, and even if it was set with lodash it didn't work for first 2 calls so avoided using get helper.
NHUB-244

fix reading of client config

---

newsroom/push.py
newsroom/signals.py

add signal when item is pushed to NH

---

assets/agenda/components/AgendaCalendarAgendaFilter.jsx
assets/agenda/components/AgendaCoverageExistsFilter.jsx
assets/agenda/components/AgendaDropdown.jsx
assets/agenda/components/AgendaDropdownFilter.jsx
assets/agenda/components/AgendaItemTypeFilter.jsx
assets/components/Dropdown.jsx
assets/components/DropdownFilter.jsx
assets/components/MultiSelectDropdown.jsx

this closes it on re-render which happens when something is selected, had to inline the button otherwise it wouldn't get the ref which it needs to initialize the menu properly (the menu must be next element).
NHUB-295

fix filter dropdown

---

newsroom/users/views.py
tests/core/test_users.py

to match the required format
NHUB-274

fix sections/products data stored for new users

---

newsroom/users/views.py

allow company admins to reset password

---

assets/company-admin/components/CompanyAdminApp.jsx
assets/users/components/EditUser.jsx
assets/users/components/EditUserProductPermission.jsx
assets/users/components/Users.jsx
assets/users/reducers.js

Also updates dynamically the seat count / max reached in the form, based on the changes in the form (to reflect the changes once the form has been saved)

[CPCN-132] fix(ui): Unable to unassign product seat if max reached

---

newsroom/push.py
tests/core/test_push_events.py

seems like elastic keeps the previous flag so make sure we reset it on update.
SDCP-694

avoid both no_end_time and all_day flags to be set

---

data_updates/00010_20230427-151329_users.py

fix user sections stored as list during migration

---

assets/company-admin/components/CompanyAdminApp.jsx
assets/general-settings/components/GeneralSettingsApp.jsx
newsroom/search.py
newsroom/settings.py
newsroom/users/users.py
newsroom/web/default_settings.py
tests/search/test_user_products.py

Allows CompanyAdmins to manage their user section and product permissions, otherwise only allow admins to manage them.

[CPCN-138] New Setting: ALLOW_COMPANIES_TO_MANAGE_PRODUCTS

---

features/web_api/companies_products.feature
newsroom/companies/companies.py
newsroom/tests/web_api/steps.py

Looks like the behave tests we passing before when they should have failed, have also fixed this up

[CPCN-137] fix(api): Company product changes result in incorrect user products assigned

---

docs/openapi.yaml
newsroom/factory/app.py
newsroom/topics/__init__.py
newsroom/topics/folders.py
newsroom/topics/topics.py
newsroom/web/default_settings.py
requirements.txt
tests/core/test_topics.py

there is one for user folders and another for company folders
CPCN-148

implement topic folders APIs

---

assets/company-admin/components/CompanyUsers.jsx

https://sofab.atlassian.net/browse/NHUB-289?focusedCommentId=122408

Fix : remove the products info and numbers from the Users tab based on key allow_companies_to_manage_products [NHUB-289]

---

assets/company-admin/components/CompanyDetails.jsx
assets/company-admin/components/CompanyDetailsProductRow.jsx
assets/company-admin/selectors.js
assets/users/components/EditUserProductPermission.jsx
messages.pot

such products are always available to company users so don't show there limits and display it as selected in user sidebar.
NHUB-290

handle unlimited products in the UI

---

newsroom/__init__.py
newsroom/agenda/agenda.py
newsroom/web/default_settings.py
newsroom/wire/items.py
tests/core/test_agenda.py
tests/core/test_wire.py

setup elastic analyzer to handle non ascii characters
CPCN-24

handle french accents in search

---

webpack.config.js

so it can be used inside docker

generate manifest.json file on disk when using webpack dev server

---

assets/search/components/SearchResultsBar/SearchResultTagsList.jsx
assets/search/components/SearchResultsBar/SearchResultsAdvancedSearchRow.jsx
assets/search/components/SearchResultsBar/index.jsx
e2e/cypress/e2e/wire/advanced_search.cy.js
e2e/cypress/support/containers/searchResultsBar.js

@petrjasek I forgot to add the new configurable fields to the search results bar

[CPCN-208] fix: Add available field names to SearchResultsAdvancedSearchRow

---

assets/search/components/SearchResultsBar/SearchResultsAdvancedSearchRow.jsx
features/web_api/wire_advanced_search.feature
newsroom/search/service.py

allow wildcards in advanced search fields

---

assets/search/components/TopicEditor.jsx
assets/user-profile/actions.js
newsroom/topics/views.py

fix folders dropdown when switching from user to company topic

---

assets/layout/components/BaseApp.jsx
assets/search/components/SearchBar.jsx
e2e/cypress/e2e/wire/topics.cy.js

Also don't render the `Show Search Tips` button in the settings pages

[CPCN-232] Clear TopSearchBar query when opening AdvancedSearchPanel

---

assets/user-profile/actions.js

for topics created by different user
CPCN-241

fix remove topic from folder action url

---

assets/search/components/TopicEditor.jsx

avoid mixing wire/agenda folders in topics editor

---

assets/search/components/FollowedTopics.jsx
assets/search/components/TopicEditor.jsx
assets/user-profile/actions.js
newsroom/web/default_settings.py

use the proper url for folders and disable caching of the api responses so that it won't list those deleted ones next time.
CPCN-243

fix deleting of company folders

---

newsroom/users/users.py
tests/core/test_user_dashboards.py

add dashboards field to user schema

---

assets/navigations/components/EditNavigation.tsx
assets/products/components/EditProduct.tsx

Fix tab switching in products and global topics

---

assets/users/components/EditUser.jsx
e2e/.npmrc
e2e/cypress/e2e/settings/users.cy.js
e2e/cypress/support/pages/layout.js
e2e/cypress/support/pages/settings_users.js
newsroom/auth/utils.py
newsroom/auth/views.py
newsroom/template_filters.py
newsroom/templates/base_layout.html
newsroom/templates/impersonate_user.html
newsroom/web/factory.py

allows admins to impersonate other users and do some setup on their behalf.
CPCN-42

impersonate feature

---

assets/search/components/TopicEditor.tsx

Fix company topics tab switching

---

newsroom/web/default_settings.py

disable stop words filter in elastic

---

assets/home/components/HomeApp.tsx

when there is personal dashboard defined
CPCN-59

fix handling of empty dashboard

---

newsroom/users/users.py
tests/search/fixtures.py
tests/search/test_user_products.py

allow public users to edit their dashboards

---

newsroom/search/service.py
newsroom/tests/fixtures.py
newsroom/wire/views.py
tests/core/test_user_dashboards.py
tests/search/test_search_filters.py
tests/search/test_user_products.py

filtering based on assigned products didn't work
properly for public users.
CPCN-59

make items in dashboard consistent with wire view

---

newsroom/agenda/agenda.py
newsroom/search/service.py
newsroom/web/default_settings.py
newsroom/wire/search.py
tests/search/test_search_fields.py
tests/search/test_search_filters.py

make fields used in query_string configurable

---

tsconfig.json

should be faster and easier due to less changes done to the code

use es2015

---

assets/agenda/components/AgendaCoverageExistsFilter.tsx
newsroom/agenda/agenda.py
tests/core/test_agenda.py

https://github.com/superdesk/superdesk-stt/pull/40
https://github.com/superdesk/superdesk-planning/pull/1844

Add Coverage Not Decided to Coverage Status filter [STTNHUB-198] [STTNHUB-203]

---

assets/server.ts
assets/users/actions.ts
assets/utils.tsx
newsroom/users/views.py
tests/core/test_users.py

there could be old data in user settings view
and then it would override any changes done via
reset password.
NHUB-346
eventually we should probably drop those views and use api directly, but didn't want to change it too much at this stage

avoid updating users with old data

---

assets/search/components/SearchResultsBar/SearchResultTagsList.tsx
assets/search/components/SearchResultsBar/SearchResultsAdvancedSearchRow.tsx
assets/search/components/SearchResultsBar/index.tsx
assets/search/components/TopicForm.tsx

Fix auto refresh 

---

assets/components/PersonalizeHomeModal.tsx
assets/components/cards/render/MoreNewsButton.tsx
assets/components/cards/render/PictureTextCard.tsx
assets/home/components/HomeApp.tsx
assets/styles/custom-modal.scss
assets/utils.tsx

Improve modal style, data, texts, more news button and more

---

assets/agenda/components/AgendaContacts.tsx
assets/agenda/components/AgendaList.tsx
assets/agenda/components/AgendaListItem.tsx
assets/agenda/components/AgendaListItemIcons.tsx
assets/agenda/components/AgendaMeta.tsx
assets/agenda/utils.ts
assets/interfaces/agenda.ts
assets/interfaces/index.ts
assets/utils.tsx

moved it from preview to a new component and used that in the list.
also added some initial types for agenda items.
CPCN-23

add event contacts info to lists view

---

assets/search/components/FollowedTopics.tsx
assets/search/components/TopicForm.tsx

- disable remove from folder
- make folder dropdown readonly in the topic editor
- hide create folder button in the company view
CPCN-247

fix company topic management for users without manage permissions

---

assets/agenda/utils.ts
assets/components/FormSection.jsx
assets/interfaces/topic.ts
assets/search/components/TopicEditor.tsx
assets/user-profile/actions.ts
assets/user-profile/reducers.ts

fix public user subscription handling for company topics

---

assets/user-profile/actions.ts

change delete folder message

---

assets/user-profile/components/UserProfileApp.tsx
newsroom/companies/__init__.py
newsroom/users/views.py

only show sections in admin profile which are actually enabled

---

assets/search/components/TopicForm.tsx

add message on topic panel in case no foldrest do yet exist

---

assets/search/components/SearchResultsBar/SearchResultsAdvancedSearchRow.tsx
e2e/cypress/e2e/wire/advanced_search.cy.js
e2e/cypress/e2e/wire/topics.cy.js
e2e/cypress/support/containers/searchResultsBar.js

avoided duplicated code, there was a bad param in one of the 3 sections
CPCN-318

fix missing remove btn in advanced search bar

---

newsroom/push.py
newsroom/tests/conftest.py
newsroom/web/default_settings.py

handle notifications on push via celery

---

assets/agenda/components/AgendaCoverages.tsx

* Handle case if _Agenda_ item `coverage.genre` is `null`

Fix : Blank screen issue in Agenda list if click on a event with coverages [NHUB-373]

---

newsroom/section_filters/section_filters.py
newsroom/utils.py
tests/core/test_wire.py

cache section filters

---

newsroom/agenda/agenda.py
tests/core/test_agenda.py

Fix related to this comment :- https://sofab.atlassian.net/browse/NHUB-361?focusedCommentId=124035

update elastic query for not planned coverage_status [NHUB-361]

---

assets/styles/custom.scss
newsroom/templates/base_layout.html
newsroom/templates/company_expiry_alert_user.html
newsroom/templates/company_expiry_alert_user.txt
newsroom/templates/page-copyright.html
newsroom/web/default_settings.py
tests/core/test_agenda.py
tests/core/test_topics.py
tests/core/test_wire.py

avoid AAP references in default theme

---

newsroom/search/service.py
tests/search/test_search_fields.py
tests/search/test_search_filters.py

use elastic cross fields search by default

---

assets/components/FormSection.tsx
assets/search/components/SearchResultsBar/SearchResultsTopicRow.tsx
assets/search/components/SearchResultsBar/index.tsx
assets/search/components/TopicForm.tsx
assets/wire/components/WireApp.tsx
e2e/cypress/e2e/wire/advanced_search.cy.js
e2e/cypress/e2e/wire/topics.cy.js

Initially open some of the dropdowns

---

assets/home/components/HomeApp.tsx

If the client doesn't have wire configured don't show dashboard personalization option

---

assets/search/components/SearchResultsBar/index.tsx
assets/wire/components/WireApp.tsx
e2e/cypress/e2e/wire/advanced_search.cy.js

Improve initially open condition

---

newsroom/auth/utils.py
newsroom/users/users.py
tests/core/test_topics.py

fix topics subscription for public users

---

newsroom/web/default_settings.py
newsroom/web/worker.py

populate SERVER_NAME based on CLIENT_URL

---

newsroom/web/worker.py

setdefault didn't set it as it was already populated by the app.
NHUB-380

fix SERVER_URL config in celery worker

---

assets/search/components/SearchResultsBar/index.tsx
assets/wire/components/WireApp.tsx

Searchbar fixes

---

assets/search/components/TopicEditor.tsx

Reload folders on creation of a new one

---

assets/search/components/SearchResultsBar/SearchResultTagsList.tsx
assets/search/components/SearchResultsBar/SearchResultsAdvancedSearchRow.tsx
assets/search/components/SearchResultsBar/SearchResultsQueryRow.tsx
assets/search/components/TopicForm.tsx

Refresh on clear, through the different buttons

---

assets/user-profile/components/EditNotificationScheduleModal.tsx

User schedule notifications improvement

---

assets/search/components/FollowedTopics.tsx
assets/search/components/TopicEditor.tsx
assets/search/components/TopicFolder.tsx
assets/search/components/TopicFolderActions.tsx
assets/search/components/TopicForm.tsx
assets/search/components/TopicList.tsx
assets/user-profile/actions.ts
assets/user-profile/reducers.ts
assets/user-profile/selectors.ts
assets/users/components/EditUser.tsx

Folders code restructuring and small bug fix

---

assets/search/components/TopicForm.tsx

Notification schedule improvements

---

newsroom/agenda/agenda.py
newsroom/push.py
tests/search/test_search_topics.py

fix items query for agenda notifications

---

assets/search/components/TopicForm.tsx

CPCN-334
Not displaying the schedule settings for 'real-time' as well.

Notifications schedule display

---

assets/search/actions.ts
assets/user-profile/actions.ts
assets/user-profile/components/UserProfileApp.tsx
newsroom/topics/topics.py
newsroom/topics/views.py
newsroom/users/views.py

and move topic handling to topics module
NHUB-370

enable email notifications when subscribing to company topic

---

assets/agenda/components/AgendaListItem.tsx
assets/agenda/components/AgendaLongDescription.tsx
assets/agenda/utils.ts

break lines description

---

assets/agenda/components/AgendaApp.tsx
assets/wire/components/ListViewControls.tsx
assets/wire/components/WireApp.tsx

Decouple controls from search

---

newsroom/users/users.py
tests/core/test_users.py

populate sections based on company when new user is created

---

assets/search/components/TopicEditor.tsx

fix notifications config on new company topics

---

assets/agenda/components/AgendaApp.tsx

Toggle dropdown on item type change in Agenda

---

newsroom/notifications/send_scheduled_notifications.py
newsroom/templates/scheduled_notification_topic_matches_email.txt
tests/core/test_send_scheduled_notifications.py

fix scheduled notification template

---

newsroom/users/views.py
tests/core/test_users.py

it didn't work when using the company admin properly
NHUB-386

populate sections for new user based on company

---

assets/interfaces/seat.ts
assets/users/components/EditUserProductPermission.tsx
assets/users/reducers.ts
assets/users/utils.ts

fix select all products

---

assets/agenda/components/AgendaApp.tsx
assets/interfaces/seat.ts
assets/search/components/SearchResultsBar/index.tsx
assets/users/components/EditUserProductPermission.tsx
assets/users/reducers.ts
assets/users/utils.ts
newsroom/news_api/default_settings.py
newsroom/tests/news_api/environment.py

Agenda item type filter improvements

---

assets/components/cards/TimePicker.tsx
assets/styles/app.scss
assets/styles/custom-forms.scss
assets/styles/time-picker.scss
assets/user-profile/components/EditNotificationScheduleModal.tsx

Create time picker component

---

assets/agenda/components/LocationFilter.tsx
assets/components/Dropdown.tsx

Quick filter imrpovements

---

assets/user-profile/actions.ts

Fix folder fetching in the case when the user doesn't have a company

---

assets/agenda/components/AgendaListItem.tsx
assets/agenda/components/AgendaLongDescription.tsx
assets/styles/article-list.scss

How to present event description in list view

---

assets/interfaces/topic.ts
assets/search/components/TopicEditor.tsx
assets/search/components/TopicFolderEditor.jsx
assets/search/components/TopicForm.tsx
assets/user-profile/actions.ts

Folder creation on topic save

---

newsroom/auth/saml.py
newsroom/auth/utils.py
tests/core/test_auth_providers.py

fix login via google

---

assets/wire/components/PreviewTagsSubjects.tsx

make it possible to hide subject with specific scheme

---

newsroom/agenda/views.py
newsroom/auth/__init__.py
newsroom/auth/utils.py
newsroom/exceptions.py
newsroom/factory/app.py
newsroom/templates/authorization_error.html
newsroom/tests/conftest.py
newsroom/wire/views.py
tests/core/test_wire.py

check for user products in the view

---

assets/styles/custom-variables.scss
assets/styles/icon-button.scss
assets/user-profile/components/EditNotificationScheduleModal.tsx

https://sofab.atlassian.net/browse/CPCN-362

Add the option to enable/disable the timepicker to set scheduled notifications

---

assets/agenda/components/AgendaMetaTime.tsx

Introduce a Planning item icon in the NH Agenda list views

---

assets/agenda/components/AgendaCalendarAgendaFilter.tsx
assets/agenda/components/AgendaCoverageExistsFilter.tsx
assets/agenda/components/AgendaDropdown.tsx
assets/agenda/components/AgendaFilters.tsx
assets/agenda/components/AgendaItemTypeFilter.tsx
assets/agenda/components/LocationFilter.tsx
assets/company-admin/components/CompanyDetailsProductFilter.tsx
assets/components/Dropdown.tsx
assets/components/DropdownFilter.tsx
assets/components/DropdownFilterButton.tsx
assets/users/components/filters/UserListCompanyFilter.tsx
assets/users/components/filters/UserListSortFilter.tsx

Quick filters improvements

---

assets/components/Dropdown.tsx

Fix value class dropdown for quick filters

---

assets/agenda/components/LocationFilter.tsx
assets/components/DropdownFilterButton.tsx

Location filter structure fix

---

assets/components/Dropdown.tsx
assets/search/components/TopicForm.tsx

Add folder icon to every dropdown option. Add dropdown full width option

---

assets/users/components/EditUserProductPermission.tsx
assets/users/reducers.ts
assets/users/utils.ts

fix select all products v3

---

.dockerignore
e2e/docker-compose.yml
e2e/server/Dockerfile
e2e/server/scripts/start.sh
e2e/server/settings.py
newsroom/webpack.py

start the server via:
```bash
$ cd e2e
$ docker-compose up server
```

add config for e2e server using docker

---

newsroom/templates/scheduled_notification_topic_matches_email.fr_ca.html
newsroom/templates/scheduled_notification_topic_matches_email.fr_ca.txt

Scheduled notification email template - FR version

---

assets/components/cards/TimePicker.tsx
assets/user-profile/components/EditNotificationScheduleModal.tsx
assets/utils.tsx

set timestamp format based on the NH settings

---

assets/agenda/components/AgendaCalendarAgendaFilter.tsx
assets/agenda/components/AgendaDropdown.tsx
assets/components/DropdownFilter.tsx

Improvements

---

assets/search/components/SearchResultsBar/index.tsx

remove 'Sort by' drop down in the Calendar/Agenda section [CPCN-409]

---

newsroom/auth/oauth.py
newsroom/auth/utils.py
newsroom/auth/views.py
newsroom/decorator.py
newsroom/templates/login_form.html

to make it work with sso and to avoid open redirect vulnerability
CPCN-368

store next page in session instead of url

---

assets/components/cards/render/CardFooter.jsx
assets/components/cards/render/CardMeta.jsx
assets/components/cards/render/LargePictureTextCard.jsx
assets/components/cards/render/LargeTextOnlyCard.jsx
assets/components/cards/render/PictureTextCard.jsx
assets/components/cards/render/TextOnlyCard.jsx
assets/components/cards/render/TopNewsOneByOneCard.jsx
assets/components/cards/render/TopNewsTwoByTwoCard.jsx
assets/styles/index.scss
assets/ui/components/ArticleBodyHtml.jsx
assets/ui/components/ArticleMedia.jsx
assets/wire/components/ItemDetails.jsx
assets/wire/components/PreviewMeta.jsx
assets/wire/components/WireListItem.jsx
assets/wire/components/WireListItemIcons.jsx
assets/wire/components/WirePreview.jsx
assets/wire/utils.js
newsroom/upload.py
tests/core/test_push.py
tests/core/test_push_events.py

[NHUB-315] (2.4.2): Support Audio & Video for Featuremedia

---

newsroom/templates/base_layout.html
newsroom/web/default_settings.py

Introduce show_date config option

---

assets/components/PersonalizeHomeModal.tsx

remove agenda link form personalize home modal

---

assets/styles/tips-content.scss
newsroom/templates/search_tips_regular.html

update tips tabs content

---

newsroom/auth/utils.py
newsroom/utils.py
newsroom/wire/views.py
tests/core/test_auth.py

fix account is disabled error for saml users

---

newsroom/auth/views.py

so that existing email addresses can't be guessed
NHUB-429

avoid specific messages for password reset

---

e2e/cypress/support/forms/editCompany.js
newsroom/topics/topics.py

validate navigations assigned to topic

---

newsroom/news_api/news/atom/atom.py
newsroom/templates/reports_print.html
requirements.txt

use released version of superdesk and planning

---

newsroom/users/users.py

to fix password reset
CPCN-434

revert user validation changes

---

assets/wire/components/filters/FilterGroup.tsx

Show search conditionally

---

newsroom/template_filters.py
newsroom/web/default_settings.py
tests/core/test_template_filters.py

fix schedule notification email date format

---

assets/agenda/components/AgendaList.tsx
assets/agenda/reducers.ts

fix : Download button is not display in agenda view

---

newsroom/history.py
newsroom/notifications/send_scheduled_notifications.py
newsroom/push.py
tests/core/test_realtime_notifications.py
tests/core/test_send_scheduled_notifications.py

[CPCN-442] fix: Only send 1 email to a user per item on push

---

newsroom/companies/companies.py
newsroom/products/products.py
newsroom/products/types.py
newsroom/users/users.py

make section required in products reference

---

assets/users/components/EditUser.tsx

Fix no company selected bug

---

assets/wire/components/filters/FilterGroup.tsx

Search disapearing fix

---

newsroom/push.py
newsroom/web/default_settings.py

make wire notifications on correction configurable

---

assets/interfaces/common.ts
assets/interfaces/content.ts
assets/interfaces/index.ts
assets/wire/actions.ts
assets/wire/components/ListItemNextVersion.tsx
assets/wire/components/ListItemPreviousVersions.tsx
assets/wire/components/WireListItem.tsx
assets/wire/components/fields/PreviousVersions.tsx
assets/wire/tests/actions.spec.ts
assets/wire/utils.ts

[CPCN-27] Show segment instead of version for transcripts

---

newsroom/company_expiry_alerts.py
newsroom/monitoring/email_alerts.py
newsroom/notifications/send_scheduled_notifications.py

so it won't create a new error on sentry every time but can aggregate those together.

avoid unique error messages

---

assets/search/components/SearchResultsBar/index.tsx

Change the text on the Sort by drop down options

---

assets/search/components/SearchResultsBar/SearchResultsFiltersRow.tsx

When selecting a location filter drop down in the calendar the page goes blank

---

assets/agenda/components/AgendaApp.tsx
assets/agenda/components/AgendaDateNavigation.tsx
assets/styles/index.scss
design_app/src/components/MainLayout.jsx
newsroom/templates/base_layout.html

- [x ] This pull request is not adding new forms that use redux

STTNHUB-288

---

data_updates/00012_20231127-133756_topics.py

[NHUB-446] chore: DB Migration script for topic subscribers

---

assets/search/components/SearchResultsBar/SearchResultsFiltersRow.tsx

[NHUB-449] fix: Save new Agenda topic not showing form

---

assets/auth/firebase/login.ts
newsroom/auth/forms.py
newsroom/auth/views.py
newsroom/templates/change_password.html
newsroom/templates/layout_wire.html
newsroom/templates/login_form.html

add link to reset password on password change page

---

newsroom/email.py
newsroom/template_filters.py

improve the usage of Babel in multilingual contexts to convert dates & times [NHUB-182]

---

assets/agenda/components/AgendaApp.tsx
assets/search/components/SearchResultsBar/index.tsx
assets/wire/components/WireApp.tsx

Show new items indicator also on the main page of Wire and Agenda

---

assets/wire/components/PreviewMeta.tsx
assets/wire/components/fields/DurationLabel.tsx
assets/wire/components/fields/index.tsx

Display duration on Preview and Detail View for a segment of a TV/radio transcript

---

newsroom/users/views.py
tests/core/test_users.py

allow both company filter and user search
NHUB-457

fix user search in company admin

---

assets/interfaces/content.ts
assets/ui/components/ArticleAbstract.tsx
assets/wire/components/ItemDetails.tsx
assets/wire/components/WirePreview.tsx
assets/wire/tests/actions.spec.ts
assets/wire/utils.ts
package-lock.json

Media gallery carousel improvements

---

assets/agenda/actions.ts
assets/agenda/utils.ts
newsroom/agenda/views.py

Also fixed issue with Agenda Bookmarks page not showing any results

[NHUB-241] fix(agenda): Push saved_items notification on coverage watch change

---

newsroom/push.py
newsroom/signals.py
tests/core/test_push_events.py

add publish_event and publish_planning signals

---

assets/users/components/EditUser.tsx

If a user is being created don't show the resend invite button

---

assets/company-admin/components/CompanyDetailsProductFilter.tsx
assets/components/SelectInput.tsx

Show products that are for the current company only

---

assets/wire/components/ItemDetails.tsx

Feature media separate from carousel

---

newsroom/companies/utils.py
newsroom/reports/reports.py
tests/core/test_reports.py

In this PR, I updated reports `Products per company, Company, Companies per product`.

Fix : Reports that are not working [NHUB-338]

---

assets/interfaces/agenda.ts
newsroom/agenda/agenda.py
newsroom/push.py
tests/core/test_push_events.py

populate coverage assigned desk user data

---

newsroom/topics/topics.py

FIX : Real Notifications are not saved on revisiting when switching from Company topics to My topics [CPCN-413]

---

newsroom/companies/views.py

handle case when `data["is_enabled"] = False`

FIX : Cannot disable a company [NHUB-473]

---

assets/company-admin/components/CompanyAdminApp.tsx

company and user search in the Company admin view should be cleared upon switching tabs [NHUB-462]

---

assets/components/cards/render/WireListCard.tsx
assets/components/cards/utils.ts
assets/wire/components/WireListItem.tsx
newsroom/cards/cards.py
newsroom/wire/__init__.py

Wire list card implementation

---

newsroom/navigations/views.py
tests/core/test_navigations.py

invlidate products cache when updating navigation products

---

assets/agenda/item-actions.ts

Remove "remove" action from agenda only

---

assets/search/components/TopicForm.tsx

Increase the max characters for saved topic title 

---

newsroom/auth/utils.py

fix case sensitive google auth

---

assets/styles/custom-variables.scss
assets/styles/index.scss

[NHUB-478] Skeleton color fix

---

newsroom/auth/__init__.py
newsroom/auth/saml.py
newsroom/auth/views.py
newsroom/web/default_settings.py

there is an error in newsroom-app repo

fix circular import error

---

newsroom/agenda/__init__.py
newsroom/agenda/utils.py

https://github.com/superdesk/newsroom-app-cp/pull/158

add coverage related functions to global templates [CPCN-523]

---

newsroom/users/users.py

Fix : Change password in user profile does not work for user types: Public, Company Admin, Internal [CPCN-505]

---

assets/user-profile/actions.ts
assets/user-profile/index.ts
assets/utils.tsx
assets/wire/actions.ts
assets/wire/index.ts
assets/wire/reducers.ts

Fix folder refresh in the side panel

---

newsroom/search/service.py
newsroom/web/default_settings.py
newsroom/wire/search.py

[NHUB-476] improve: Round embargo queries to nearest minute

---

newsroom/news_api/news/atom/atom.py
newsroom/push.py
newsroom/wire/items.py
tests/core/test_agenda.py

and fix issues which popped up after https://github.com/superdesk/superdesk-core/pull/2511

make find_one lookup for agenda item use mongo index

---

assets/ui/components/ArticleMedia.tsx

force reload of audio tag when switching items

---

assets/search/components/FollowedTopics.tsx
assets/search/components/TopicEditor.tsx
assets/user-profile/reducers.ts
newsroom/companies/views.py
newsroom/types.py
newsroom/utils.py

fix company users wiring for topic editor

---

newsroom/agenda/formatters/csv_formatter.py
newsroom/agenda/utils.py
newsroom/web/default_settings.py
tests/core/test_csv_formatter.py

Fix: the format of information in the CSV file for exported events [CPCN-553]

---

assets/wire/components/ItemDetails.tsx

make gallery display in item detail configurable

---

newsroom/agenda/agenda.py
newsroom/search/service.py
tests/core/test_realtime_notifications.py

fix agenda notifications not being sent

---

newsroom/navigations/navigations.py
newsroom/wire/views.py

Fix : Users unable to view content when clicking on 'Topics' [CPCN-617]

---

assets/agenda/utils.ts

fix agenda group sorting

---

newsroom/agenda/agenda.py

there are more than 100 items per day but then
it doesn't load all items for current day
CPCN-641

increase default agenda limit to 250

---

newsroom/templates/base_layout.html
newsroom/templates/public_dashboard.html
newsroom/templates/public_dashboard_base.html

add meta block to layout and make it simple to override public dashboard

---

newsroom/__init__.py
newsroom/agenda/agenda.py
newsroom/wire/items.py

Change ES mapping for urgency and priority to use 'keywords' instead of 'integer' [NHUB-477]

---

newsroom/templates/search_tips_advanced.fr_ca.html
newsroom/templates/search_tips_regular.fr_ca.html

Update French search tips

---

newsroom/push.py
newsroom/wire/items.py
tests/core/test_push_evolved.py

fix updates received out of order

---

newsroom/agenda/formatters/csv_formatter.py
tests/core/test_csv_formatter.py

handle 'None' subjects in the events.

FIX : Unable to download CSV file in the Calendar Section [CPCN-626]

---

.github/workflows/lint.yml
dev-requirements.txt
docs/requirements.txt
mypy-requirements.txt
setup.cfg

- make separate requirements for docs
- handle all mypy releated libs in mypy requirements

clean up requirements

---

newsroom/navigations/navigations.py

FIX: show all global topics to user_type Adminstrator [CPCN-617]

---

newsroom/agenda/utils.py

FIX : Real-time email alerts template doesn't update the coverage status from 'Planned' to 'Complete' or 'Cancelled' [CPCN-630]

---

assets/wire/components/ItemDetails.tsx
assets/wire/components/WirePreview.tsx
assets/wire/utils.ts

PR based on latest comment :- https://sofab.atlassian.net/browse/CPCN-670?focusedCommentId=128070

Fix : listview rendering and bodyimages rendering in detail preview [CPCN-670]

---

requirements.txt
tests/core/test_signup.py

update forms requirements

---

newsroom/section_filters/section_filters.py

fix filter error when there are section filters

---

assets/server.ts
assets/wire/actions.ts
newsroom/utils.py
newsroom/wire/views.py
tests/core/test_download.py

FIX: Update Download method from GET to POST to address URL limiter issue [CPCN-626]

---

newsroom/commands/__init__.py
newsroom/commands/elastic_reindex.py
requirements.txt

it will reindex single source index at a time
within elastic.
CPCN-625

add `elastic_reindex` command

---

data_updates/00014_20240312-085705_topics.py
newsroom/topics/__init__.py
newsroom/topics/folders.py
newsroom/topics/topics.py
tests/core/test_topics.py
tests/data_updates/test_update_missing_user_topics.py

and add an upgrade script to handle missing users
CPCN-685

delete user topics and folders when deleting a user

---

assets/agenda/actions.ts
assets/search/components/NewItemsIcon.tsx

show refresh icon when event gets unposted

---

assets/agenda/components/MultiDayListLabel.tsx

[CPCN-645] fix(ui): Cap multiday event tag to number of event days

---

assets/agenda/actions.ts

When events is update in the planning-only view, update the event-related planning items [NHUB-494].

---

assets/search/components/SearchResultsBar/SearchResultsFiltersRow.tsx

handle filters with multiple values

---

assets/agenda/actions.ts
assets/agenda/utils.ts

update check for both local and UTC time in isCoverageForExtraDay function.

---

assets/agenda/actions.ts

Refactor:coverage comparison using optional chaining

---

assets/agenda/components/MultiDayListLabel.tsx

[CPCN-734] fix(ui): Limit multiday event tag to a minimum of 1

---

newsroom/push.py
newsroom/topics/topics.py
newsroom/web/default_settings.py
tests/core/test_realtime_notifications.py

CPCN-695
uses https://github.com/superdesk/superdesk-planning/pull/1936

avoid multiple notifications for recurring events

---

e2e/cypress/e2e/company_admin/company_settings.cy.js

fix failing e2e

---

assets/interfaces/config.ts
assets/wire/components/filters/FilterGroup.tsx

configure search bar within filter [CPCN-627]

---

assets/agenda/components/AgendaItemDetails.tsx
assets/agenda/components/AgendaListItem.tsx
assets/agenda/components/AgendaPreview.tsx
assets/agenda/components/TopStoryLabel.tsx
assets/interfaces/agenda.ts
assets/interfaces/configs.ts
assets/ui/components/Article.tsx

Visual indication for Top stories in list, preview and full view

---

newsroom/agenda/agenda.py
newsroom/news_api/news/search_service.py
newsroom/search/__init__.py
newsroom/search/service.py
newsroom/wire/search.py
tests/core/test_realtime_notifications.py
tests/search/test_search_topics.py

use filters when searching for matching topics in agenda

---

assets/agenda/components/AgendaList.tsx

Implement item sorting
