superdesk/newsroom-core

newsroom/web/default_settings.py, newsroom/web/factory.py, newsroom/webpack.py
and set default for webpack manifest path
so we don't have to put this in each app settings
SDESK-6200
=> handle theme folder in newsroom-app/server

newsroom/web/default_settings.py, newsroom/webpack.py
use assets url for client urls and server url
only for fetching the manifest.
=> fix webpack assets handling for docker

assets/styles/index.scss, assets/wire/components/ItemDetails.jsx, assets/wire/components/WirePreview.jsx, assets/wire/components/fields/Authors.jsx
On by default, if the list of Authors is not empty for the item.
Can be turned off with the following `ui_config`
```json
[{
"_id": "wire",
"preview": {
"authors": {"displayed": false}
}
}]
```
=> [NHUB-22] Show list of Authors in Wire Preview

assets/components/NotificationList.jsx, assets/components/NotificationListItem.jsx, assets/notifications/actions.js, assets/notifications/components/BasicNotificationItem.jsx, assets/notifications/components/NotificationsApp.jsx, assets/notifications/components/notificationItems.jsx, assets/notifications/reducers.js, assets/styles/navbar.scss, newsroom/agenda/agenda.py, newsroom/notifications/__init__.py, newsroom/notifications/notifications.py, newsroom/push.py, newsroom/topics/topics.py, newsroom/topics/views.py, newsroom/users/views.py, newsroom/wire/views.py, requirements.txt, tests/core/test_agenda_events_only.py, tests/core/test_notifications.py, tests/core/test_push.py, tests/core/test_push_events.py
Improves notifications by:
* Only sending `count` with websocket notifications, and not the `notification` or `content item`
* Only loading notifications and their associated items if notification bar is open
* Adding the ability to register new notification message types
* Add new notifications for shared Wire, Agenda and Topics, as well as when new content arrives that matches a Topic
=> [NHUB-96] Improve notifications to handle more message types

data_updates/00006_20220223-155546_products.py, newsroom/companies/views.py, newsroom/news_api/news/search_service.py, newsroom/news_api/products/resource.py, newsroom/products/products.py, newsroom/products/views.py, newsroom/reports/reports.py, newsroom/search.py, newsroom/tests/fixtures.py, tests/core/test_agenda.py, tests/core/test_agenda_events_only.py, tests/core/test_companies.py, tests/core/test_navigations.py, tests/core/test_push.py, tests/core/test_reports.py, tests/core/test_wire.py, tests/fixtures.py, tests/news_api/test_api_audit.py, tests/search/fixtures.py, tests/search/test_search_filters.py
The `Management API` was specifically searching for `Company Products` using `ObjectId`, as well as updating `Navigation Companies` using `ObjectId`.
The `Web API` on the other hand was using `str` instead, so any `Company Product` permissions updated from the `Web UI` would not be returned from the `Management API`.
Instead of placing a hack fix into the `Management API`, I updated the Navigation schema to use `ObjectId`.
=> [CPNHUB-10] fix: Use ObjectId for Navigation Company IDs

assets/home/actions.js, assets/home/components/HomeApp.jsx, assets/home/reducers.js, assets/styles/app.scss, assets/styles/spinner.scss, newsroom/push.py, newsroom/web/default_settings.py, newsroom/wire/views.py
The following has been implemented to improve the home page loading times:
- Delete dashboard cache on push (so new items show up without waiting for cache timeout)
- Load the home page first, then load the card items thereafter
- Show a spinner while loading card items, so user knows items are loading
=> [NHUB-99] Improve initial load times for home page

newsroom/factory/app.py, requirements.txt
this was an issue with sentry integration:
https://github.com/getsentry/raven-python/issues/457
which resulted in empty request body so there was
no data to check signature on. switching from raven
to sentry_sdk which doesn't have that issue.
CPNHUB-96
=> fix signature check on push

assets/styles/navbar.scss
This was caused by changes in the PR https://github.com/superdesk/newsroom-core/pull/108.
@darconny I tried using Bootstrap Dropdown but it doesn't have an append to body option. Therefor this CSS rule is blocking the `Notification` and `User Profile` dropdown menus from appearing.
If you have a better solution that fixes this and the reason for this css rule in the first place, please let me know.
=> [SDCP-609] fix: Page Navbar dropdowns hidden due to css overflow

data_updates/00007_20220502-134524_products.py, features/web_api/navigations.feature, newsroom/navigations/views.py, newsroom/products/products.py, newsroom/products/views.py, newsroom/tests/web_api/steps.py, tests/core/test_agenda.py, tests/core/test_agenda_events_only.py, tests/core/test_navigations.py, tests/core/test_wire.py
Fixes bug introduced in https://github.com/superdesk/newsroom-core/pull/122
=> [CPNHUB-108] fix: Use ObjectId everywhere for product.navigations

assets/ui/components/ArticleBodyHtml.jsx
so newsroom can render embeds using those.
only executing scripts with src not inline js.
NHUB-119
=> execute scripts in body html

assets/ui/components/ArticleBodyHtml.jsx
once loaded it won't process automatically new embeds,
so instead of reloading the script call the embed api
to reload the widgets. also implemented for twitter.
NHUB-119
=> fix instagram embeds processing

assets/ui/components/ArticleBodyHtml.jsx
seems like instagram uses different codes based
on location so use just the smallest common part
to detect it.
NHUB-119
=> fix embeds handling

newsroom/email.py
we were using custom policy which doesn't do line breaks.
https://docs.python.org/3.8/library/email.policy.html#email.policy.HTTP
CPNHUB-132
=> fix sendmail error

newsroom/data_updates.py, newsroom/email.py, newsroom/tests/news_api/steps.py, newsroom/tests/steps.py, tests/core/test_emails.py
according to RFC 5322 any line in an email can't be longer than 998
characters so try to pretty print the html which reformats it
instead of printing everything on a single line, also enforce
line limit on text via splitting longer lines.
CPNHUB-132
=> avoid long lines in email body

assets/agenda/components/CoverageItemStatus.jsx, features/news_api/news_api_atom.feature, messages.pot, newsroom/tests/news_api/steps.py
Temporary workaround for strings coming from Superdesk/Planning
=> [CPNHUB-24] fix translation of cancelled planning & coverages

assets/agenda/components/AgendaEdNote.jsx, messages.pot
=> fix agenda ednote english strings from sd

assets/agenda/components/AgendaList.jsx, assets/agenda/components/AgendaPreviewPlanning.jsx, assets/agenda/utils.js, features/web_api/agenda_search.feature, newsroom/agenda/agenda.py
Fixes the issue where planning/coverages were still shown if another planning/coverage matched from same parent Event
=> [STTNHUB-177] fix: Add coverage hits to search results

assets/agenda/utils.js
use moment utc mode for event start/end when
it's all_day/no_end_time event so it will render
proper date and won't do any conversion.
CPNHUB-167
=> fix agenda group date for all day events

assets/agenda/utils.js
one day events with `all_day=True` might have same start and end date timestamp and that would not match any day with `isBetween` so implement comparison that handles it.
CPNHUB-167
=> fix agenda date group mapping

newsroom/search.py
This was happening when pushing Agenda items and checking for matching Topics.
```
ERROR:newsroom.push:'SearchQuery' object has no attribute 'planning_items_should'
Traceback (most recent call last):
File "/opt/newsroom/env/lib/python3.8/site-packages/newsroom/push.py", line 703, in notify_new_item
notify_agenda_topic_matches(item, user_dict, company_dict)
File "/opt/newsroom/env/lib/python3.8/site-packages/newsroom/push.py", line 798, in notify_agenda_topic_matches
topic_matches = superdesk.get_resource_service("agenda").get_matching_topics(
File "/opt/newsroom/env/lib/python3.8/site-packages/newsroom/agenda/agenda.py", line 1226, in get_matching_topics
return self.get_matching_topics_for_item(
File "/opt/newsroom/env/lib/python3.8/site-packages/newsroom/search.py", line 668, in …
```
=> fix(push/notify): Add default value for search.planning_items_should

assets/company-reports/actions.js, newsroom/reports/content_activity.py
`date_from` and `date_to` is stored used number not string, and was throwing the following:
```
newsroom_js.5b7207d103d2857d2911.js:332 Uncaught TypeError: dateString.substring is not a function
at getDateInputDate (newsroom_js.5b7207d103d2857d2911.js:332:43)
at getReportQueryString (company_reports_js.cbe68e636033e691c9f6.js:2766:60)
at company_reports_js.cbe68e636033e691c9f6.js:2870:27
at common.29dfbea423aa904b3128.js:33153:18
```
Was also throwing this on the backend:
```
File "/home/marklark/miniconda3/envs/cp-nhub/lib/python3.8/site-packages/newsroom/reports/content_activity.py", line 303, in get_content_activity_report
for items in get_items(args):
File "/home/marklark/miniconda3/envs/cp-nhub/lib/python3.8/site-packages/newsroom/reports/content_activity.py", line 60, in get_items …
```
=> Fix report date formatting

newsroom/agenda/agenda.py, newsroom/push.py, newsroom/search.py, newsroom/wire/search.py, tests/search/test_search_params.py
From what I could tell, `_type` was required in searches as Agenda items used to be stored in the `items` resource. This was changed before first production release of Newsroom, so we don't need this anymore.
It also looks like linking of Content to Coverages changed this `_type` on push.
=> [CPNHUB-159] fix(search): Dont add _type to resource searches

newsroom/email.py
Using SMTPUTF8 was causing issues with some subjects not rendering properly in Outlook. Based on the docs `Useful for serializing messages to a message store without using encoded words in the headers`.
=> [CPNHUB-157] fix(email): Use SMTP so headers are escaped

newsroom/topics/topics.py
This is required as there is no way to know who to return the Topic to if it is converted from a `Company Topic` to a `My Topic`.
=> [CPNHUB-179] fix(schema): Make `user` attribute mandatory for Topics

assets/agenda/tests/utils.spec.js, assets/agenda/utils.js
when using from filter it can go before selected day on top
and then no items were visible
CPNHUB-196
=> fix agenda items display when filtering by date

assets/layout/components/BaseApp.jsx, assets/wire/components/ItemsList.jsx, assets/wire/components/WireApp.jsx
the scroll event doesn't bubble to parent in react 17 so the handler must be set on element which actually is scrolling.
NHUB-266 STTNHUB-232
=> fix wire scrolling

newsroom/users/views.py
As the cache delete happens on the resource service now
https://github.com/superdesk/newsroom-core/blob/develop/newsroom/users/users.py#L160.
This was causing an issue only where cache is enabled. From the cp-uat logs:
```
Traceback (most recent call last):
File "/opt/newsroom/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/opt/newsroom/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/newsroom/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/newsroom/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File …
```
=> [NHUB-263] fix(user_update): Remove unnecessary cache delete in blueprint

assets/user-profile/actions.js, newsroom/users/users.py, newsroom/users/views.py
@petrjasek I created a new endpoint specifically for updating of User Profiles, as we've had numerous issues around creating/updating users between the profile page and settings page (section & product privileges being lost, profile data not being saved etc).
Having a dedicated endpoint that only allows `USER_PROFILE_UPDATES` reduces the risks of breaking the ability to save a User Profile
=> [CPCN-110] fix: Create separate endpoint to update User Profile

newsroom/settings.py, tests/core/test_settings.py
A bug with boolean settings, such as `allow_companies_to_manage_products`, where a valid `False` value was not being stored in `flask.g.settings`, resulting in the default value being used instead.
=> [CPCN-138] fix(api): Include False values when generating flask.g.settings

assets/users/components/filters/UserListSortFilter.jsx
This will sort by users who have validated their account and logged in at least once, vs those who have never logged in
=> [CPCN-139] fix(ui): Sort users by is_validated instead of is_enabled

newsroom/email_templates.py
`safe` was only applied to the last variable when expanding template vars
=> [CPNHUB-157] fix: Email subjects include html entities from template vars

features/web_api/user_permissions.feature, newsroom/auth/utils.py, newsroom/users/users.py
Also show all sections to admin users, regardless of config (similar to how we're allowing all products, regardless of admin user settings).
=> [CPCN-155] fix(api): User update logic uses previous company when removing the company

assets/companies/actions.js, assets/companies/components/CompanyPermissions.jsx, assets/companies/components/EditCompany.jsx, assets/companies/reducers.js, features/web_api/companies_products.feature, newsroom/companies/companies.py, newsroom/companies/views.py, tests/core/test_companies.py, tests/core/test_products.py
The previous logic used to separate out company permission api complicated things from the front-end. Now we're adding the ability to save company product/section permissions from the same endpoint to update a company, thus reducing the logic to calculate the new section/product for a company.
There was also a bug in the company update logic, if `updates['products'] == []`, then the original products would be used instead.
=> [CPCN-153] fix: Send company product updates via company endpoint

.github/workflows/e2e.yml, .github/workflows/tests.yml, assets/companies/components/EditCompany.jsx, assets/companies/components/EditCompanyDetails.jsx, assets/companies/reducers.js, newsroom/auth/saml.py, newsroom/auth/views.py, newsroom/companies/companies.py, newsroom/companies/views.py, newsroom/templates/layout_login.html, newsroom/templates/login_client.html, newsroom/templates/login_locale_dropdown.html, newsroom/web/default_settings.py, requirements.txt, tests/core/test_saml.py
we can set on company email domain which will be tested when authenticating via saml and if user email matches it it will assign the company to user.
there is also new config for custom client saml configs which allows us to configure user specific login page which picks the config to be used for SAML auth. then it uses the company domain to match the config value.
STTNHUB-222
=> improve saml config options

assets/layout/components/BaseApp.jsx
This is required as we're clearing the TopSearch bar query, and item's weren't reflecting this
=> [CPCN-232] fix(ui): Reload items when opening AdvancedSearch panel

newsroom/companies/companies.py, newsroom/companies/views.py
* Set the default value from web api in the views and not the resource
* Allow company_create signal to define it's own defaults (such as in mgmt_api)
=> [CPNHUB-248] fix: Change companies.auth_provider to be optional

assets/agenda/utils.ts
it was limiting it based on current date but bookmarked events might be shown anytime, so limit it to be max 10 days from the start.
NHUB-335
=> fix agenda bookmarks not visible

newsroom/search/service.py, tests/core/test_wire.py
remove cross_fields type from the highlights query
CPCN-339
=> fix es highlights with multi word queries

newsroom/company_admin/views.py, newsroom/products/products.py, newsroom/products/views.py, newsroom/users/users.py, tests/core/test_products.py, tests/search/test_user_products.py
when there was empty products field on company
it would use all active products.
NHUB-390
=> fix company with no products getting all content

assets/company-admin/components/CompanyAdminApp.tsx, assets/users/actions.ts, assets/users/components/EditUser.tsx, assets/users/components/Users.tsx, assets/users/reducers.ts
NHUB-401
There is a bug in the initial implementation. It crashes when there are more products that are not being displayed in the user>products section. When trying to "select all" I was selecting ALL that were in the redux store, rather than all that were rendered in the products section. I fixed that now and also deprecated the messy `editUser` action/reducer that were coupled with DOM
=> Fix select all products v2

newsroom/email.py, newsroom/gettext.py, newsroom/template_loaders.py, newsroom/web/factory.py, tests/core/test_template_loaders.py
so when using template eg. `layout.html` it will pick `layout.fr_ca.html` if locale is set and file exists.
it will also use selected locale for time formats.
CPCN-359
=> implement locale aware template loader

newsroom/notifications/send_scheduled_notifications.py
This was due to `flask_babel.format_datetime` expects UTC and rebases for us to the configured timezone for the session (set in the `send_scheduled_notifications` command).
=> [CPCN-414] fix: Send notification schedule date in utc for templates

assets/components/PersonalizeHomeModal.tsx, assets/utils.tsx
so it's visible based on selected my/company topics.
CPCN-415
=> fix display of empty topics message

.github/workflows/lint.yml, newsroom/auth/utils.py, newsroom/users/users.py
- avoid checking permissions when storing the token
CPCN-434
=> fix password reset not working on custom cp reset page

assets/components/SidebarFolder.jsx, assets/search/components/SearchBar.tsx, assets/search/components/TopicFolder.tsx, assets/search/components/TopicFolderActions.tsx, assets/search/components/TopicFolderEditor.jsx, assets/search/components/TopicItem.tsx, assets/user-profile/components/UserProfileApp.tsx, e2e/cypress/e2e/wire/wire_topic.cy.js, e2e/cypress/support/pages/profile_topics.js
=> wire - topic e2e test

.github/pull_request_template.md
When using `lodash.get`, typescript sees fields as strings and can't provide support for finding usages, renaming and validation of types in general.
=> require replacing `lodash.get` with optional chaining for modified code

newsroom/email_templates.py, tests/core/test_email_templates.py
the cursor was already iterated over in `get_from_mongo` and then in the import task it wouldn't be able to read it again resulting in db conflicts if `email_templates` collection was already populated.
NHUB-440
=> fix email template import on init

newsroom/template_filters.py, newsroom/web/default_settings.py
it's needed for french/finnish localization
CPCN-408
=> add specific config for NOTIFICATION_EMAIL_DATETIME_FORMAT

assets/home/reducers.ts
which calls analytics but itemsById were not set there.
NHUB-430
=> fix error message when doing an action from home page

assets/wire/components/WireListItem.tsx, assets/wire/components/filters/FilterItem.tsx, assets/wire/components/filters/FiltersTab.tsx, e2e/cypress/e2e/wire/wire_action.cy.js, e2e/cypress/support/pages/filter_panel.js, e2e/cypress/support/pages/wire.js
=> Wire-Filter e2e

assets/reducers.ts
=> Refresh widget - new items indicator is missing when new items arrive to Newshub

assets/am-news/components/AmNewsListItem.tsx, assets/components/cards/render/LargePictureTextCard.tsx, assets/components/cards/render/MediaGalleryCard.tsx, assets/components/cards/render/TopNewsOneByOneCard.tsx, assets/components/cards/render/TopNewsTwoByTwoCard.tsx, assets/interfaces/content.ts, assets/wire/utils.ts
=> fix UI error when there is an association with `null` value

assets/components/cards/render/PictureTextCard.tsx, assets/components/cards/utils.ts
=> fix picture text card display error with missing picture

assets/search/actions.ts, assets/search/components/SearchResultsBar/index.tsx
=> Agenda search results fix

assets/interfaces/content.ts, assets/wire/components/PreviewMeta.tsx, assets/wire/components/fields/ExpiryDateLabel.tsx, assets/wire/components/fields/index.tsx
=> Display expiry date on Preview and Detail View for a segment of a TV/radio transcript

newsroom/auth/views.py, tests/core/test_auth.py
=> fix current password check on change password view

assets/agenda/tests/utils.spec.ts, assets/agenda/utils.ts, newsroom/agenda/agenda.py
Also only hide items that are multi-day Events
=> [NHUB-460] fix(agenda): Search all display dates

assets/agenda/utils.ts, newsroom/utils.py
=> Fix location from ingested items display

newsroom/companies/companies.py, tests/search/test_user_products.py
when company products are updated but not company sections it was
removing all user products due to missing sections data
CPCN-515
=> fix removal of user products

assets/agenda/utils.ts
the coverage date info is removed when restricted coverage is enabled but then it gets `undefined` which adds a current date to the list of item extra dates and make each event with planning data show up as starting today.
STTNHUB-305
=> fix event date grouping with restricted coverage info enabled

newsroom/gettext.py, newsroom/template_filters.py, newsroom/templates/download_agenda.txt, newsroom/web/factory.py, tests/core/test_template_filters.py
=> fix: The date in the downloaded Plain text file is not the event date [CPCN-388]

assets/agenda/components/AgendaPreviewCoverages.tsx
=> <p> tags appearing in the planning block of event items in both preview and full view

assets/components/CalendarButton.tsx
=> The language config for the date picker calendar in the Agenda section is not picked up anymore

newsroom/wire/formatters/picture.py
first use `original` rendition if it is present instead of `baseImage` in story_image downloads.
https://github.com/superdesk/newsroom-app-cp/pull/160
=> Images downloaded from NewsPro have low resolution and small size comparing to CP's legacy system [CPCN-514]

.eslintrc.js, assets/agenda/components/AgendaListItem.tsx, assets/styles/article-list.scss
=> Wire item tiles are not uniform in size for some searches

newsroom/push.py, newsroom/search/service.py, tests/core/test_push.py
so it won't fail for other users when there is a bad topic, should also avoid timeouts when checking too many products at the same time.
NHUB-479
=> when looking for matching topics run a query per user

assets/search/components/TopicEditor.tsx, assets/search/components/TopicForm.tsx, assets/user-profile/actions.ts
=> Fix topic being removed from folder on edit

newsroom/agenda/agenda.py, tests/core/test_realtime_notifications.py
in db we store an object not a string
CPCN-592 CPCN-620
=> fix agenda topics query with filter

newsroom/agenda/agenda.py, newsroom/search/service.py, tests/search/test_search_filters.py, tests/search/test_search_topics.py
so we leave more space for products
=> use `bool.must` for request query to avoid caching

assets/agenda/reducers.ts, assets/agenda/utils.ts
and also fix the from param not being updated
so it was loading same items again and again.
CPCN-640 CPCN-641
=> fix agenda groups sorting when loading more items

newsroom/cards/cards.py, newsroom/public/views.py, newsroom/types.py, newsroom/wire/items.py, newsroom/wire/search.py
we have only size config for wire list,
for the other cards it would be set to 0.
also disable the card items endpoint when
public dashboards are not enabled.
CPCN-594
=> fix empty dashboard cards

newsroom/wire/utils.py, tests/core/test_wire_utils.py
fix an error on download when picture was removed
and there is None in associations.
CPCN-649
=> fix picture download when picture was removed

assets/agenda/components/AgendaMetaTime.tsx, assets/agenda/components/AgendaTime.tsx, assets/agenda/utils.ts, assets/monitoring/components/MonitoringPanel.tsx, assets/utils.tsx
it was different based on coverages but then it wouldn't be consistent with preview etc.
CPCN-645
=> always show same date on event

assets/agenda/actions.ts, assets/agenda/reducers.ts, assets/interfaces/agenda.ts
in the agenda section's side filter panel is not fully functional due to a missing Loading Aggregations state;
=> Fix: If a topic is saved based on a side panel filter search then the rest disappear once the user returns [CPCN-560]

newsroom/agenda/agenda.py, newsroom/auth/utils.py, newsroom/decorator.py, newsroom/notifications/notifications.py, newsroom/products/products.py, newsroom/search/service.py, newsroom/template_filters.py, newsroom/tests/fixtures.py, newsroom/utils.py, newsroom/wire/items.py, newsroom/wire/search.py, tests/core/test_agenda.py, tests/core/test_agenda_events_only.py, tests/core/test_companies.py, tests/core/test_navigations.py, tests/core/test_products.py, tests/core/test_push.py, tests/core/test_realtime_notifications.py, tests/core/test_wire.py, tests/core/utils.py
to avoid sending emails based on old config
also filtering out topics for sections user does not have access to anymore
CPCN-673 CPCN-647
=> stop caching products

newsroom/celery_app.py, newsroom/errors.py, newsroom/push.py
not sure this could actually happen due to redis or so,
but shouldn't hurt in general and I'm running out of ideas
=> make sure there is just 1 worker sending notifications for a single item

assets/search/tests/actions.spec.ts, package-lock.json, package.json
it's required via karma-jasmine
=> remove top level jasmine-core dependency

newsroom/agenda/agenda.py, tests/core/test_agenda.py
Only `text` coverages include `delivery_id`. That is why in the `Planned` filter, we are seeing coverages with `workflow status` being `completed` and not having `delivery_id`.
=> Fix: when filter 'planned' coverage status, 'completed' coverages also show up in the results [CPCN-652]

assets/agenda/utils.ts
there are no planning items matching only coverages
CPCN-671
=> fix search on event metadata together with coverages filter

assets/wire/components/ItemDetails.tsx, assets/wire/components/MediaPreview.tsx, assets/wire/components/WirePreview.tsx, assets/wire/utils.ts
=> Bring back the code to show all images added to the media gallery field 'one below each other' [NHUB-499]

assets/agenda/components/AgendaListItemIcons.tsx
=> If updates to Planning items are pushed to NH they should be visible in the Agenda list views immediately [NHUB-494]

newsroom/web/default_settings.py
when running both newsroom and superdesk. both were using same default session cookie name and one would override the other.
=> avoid auto logout on localhost

assets/agenda/tests/utils.spec.ts, assets/agenda/utils.ts
always display event when it's happening and also on days when there is a coverage instead of filtering it out based on specific filtering.
CPCN-671
=> fix events not visible in the agenda

assets/users/actions.js, assets/users/components/EditUser.jsx, assets/users/reducers.js, e2e/cypress/e2e/company_admin/company_settings.cy.js, newsroom/companies/companies.py, newsroom/users/forms.py, newsroom/users/views.py
If no changes to sections were done on the front end, then keep using the company sections for permissions.
=> [TGA-86] fix: Only update user sections if they were changed

assets/users/actions.ts, assets/users/components/EditUser.tsx, assets/users/reducers.ts, e2e/cypress/e2e/company_admin/company_settings.cy.js, e2e/cypress/e2e/company_admin/product_seats.cy.js, e2e/cypress/support/forms/editUser.js, newsroom/companies/companies.py, newsroom/users/forms.py, newsroom/users/users.py, newsroom/users/views.py, tests/core/test_users.py
Same changes as https://github.com/superdesk/newsroom-core/pull/849 but for Newshub v2.5+
=> [TGA-86] fix(2.5+): Only update user sections if they were changed

newsroom/auth/__init__.py, newsroom/templates/base_layout.html, newsroom/web/factory.py
and add layout_script block which can be overriden in layout and used by all pages.
CPCN-194
=> add user to template globals

newsroom/notifications/send_scheduled_notifications.py, newsroom/wire/views.py, tests/core/test_user_dashboards.py
but had it previously.
CPCN-730
=> fix errors when user does not have access to section

assets/companies/components/EditCompanyDetails.tsx, assets/interfaces/company.ts, data_updates/00015_20240325-150938_companies.py, newsroom/auth/saml.py, newsroom/companies/companies.py, newsroom/companies/views.py, newsroom/types.py, tests/core/test_auth_providers.py, tests/core/test_companies.py, tests/core/test_saml.py
=> allow multiple auth domains per company
